#!/usr/bin/env bash
# check: vocabulary
# born: 2026-09-13
# failure: the agent used a synonym for a settled domain term, and the drift was silent because prose rules do not block a commit
# rule: no added line in the staged diff uses a synonym that the Domain section of AGENTS.md says to avoid
# limit: this catches the word, not the concept. A synonym nobody listed passes. It is a salience tool, not a semantic one.
#
# Source of the term list: the "## Domain ..." section of the root AGENTS.md. Never keep a second list here.
# Entry format, one per line:
#   - <term>: <definition>. Avoid: <synonym>, <synonym>. Avoid anywhere: <synonym>.
# "Avoid:" synonyms match as whole words only: a synonym inside a longer identifier is not a hit.
# "Avoid anywhere:" synonyms also match inside identifiers.
# Matching is case-insensitive. Only added lines count. Deleted lines and untouched code are not violations.
# Runs in the pre-commit hook and in `just check`. Both read the staged diff.
set -euo pipefail

root="$(git rev-parse --show-toplevel)"
cd "$root"

[[ -f AGENTS.md ]] || { echo "rule: vocabulary: no AGENTS.md, so no term list. Run init-agents." >&2; exit 1; }

# Parse the Domain section into "<kind>\t<synonym>\t<term>" rows. kind: word or anywhere.
rules="$(awk '
  /^## / { on = ($0 ~ /^## Domain/); if (on) seen = 1; next }
  !on || !/^- [^:]+:/ { next }
  {
    term = $0; sub(/^- /, "", term); sub(/:.*/, "", term)
    rest = substr($0, index($0, ":") + 1)
    while (match(rest, /Avoid( anywhere)?:[^.]*/)) {
      clause = substr(rest, RSTART, RLENGTH); rest = substr(rest, RSTART + RLENGTH)
      kind = (clause ~ /^Avoid anywhere:/) ? "anywhere" : "word"
      sub(/^Avoid( anywhere)?:/, "", clause)
      n = split(clause, syn, ",")
      for (i = 1; i <= n; i++) {
        s = syn[i]; gsub(/^[[:space:]]+|[[:space:]]+$/, "", s)
        if (s == "") { printf "BAD\t%d\n", NR; continue }
        printf "%s\t%s\t%s\n", kind, tolower(s), term
      }
    }
  }
  END { if (!seen) print "NOSECTION" }
' AGENTS.md)"

grep -q '^NOSECTION$' <<< "$rules" && { echo "rule: vocabulary: AGENTS.md has no '## Domain' section" >&2; exit 1; }
if bad="$(grep '^BAD' <<< "$rules")"; then
  echo "rule: vocabulary: empty synonym in an Avoid clause: AGENTS.md:$(cut -f2 <<< "$bad" | head -1)" >&2
  exit 1
fi
rules="$(grep -E '^(word|anywhere)' <<< "$rules" || true)"
[[ -n "$rules" ]] || exit 0

# Exclusions. Paths whose words this repo does not choose.
excluded() {
  case "$1" in
    # The vocabulary source names the synonyms on purpose.
    AGENTS.md|*/AGENTS.md) return 0 ;;
    # Vendored code.
    vendor/*|*/vendor/*|node_modules/*|*/node_modules/*|third_party/*|*/third_party/*) return 0 ;;
    # Lockfiles.
    go.sum|*/go.sum|bun.lock|*/bun.lock|bun.lockb|*/bun.lockb|package-lock.json|*/package-lock.json|yarn.lock|*/yarn.lock|pnpm-lock.yaml|*/pnpm-lock.yaml|packages.lock.json|*/packages.lock.json|Cargo.lock|*/Cargo.lock) return 0 ;;
    # Generated files by name.
    *.pb.go|*_gen.go|*.gen.go|*.gen.ts|*.generated.*|*.g.cs|*.Designer.cs|*.min.js|*.snap) return 0 ;;
    # Third-party APIs whose naming this repo does not control: add their client or schema paths here, one comment each.
  esac
  # Generated files by marker in the first lines of the staged blob.
  git show ":$1" 2>/dev/null | head -n 5 | grep -Eq 'Code generated .* DO NOT EDIT|@generated|<auto-generated' && return 0
  return 1
}

files=()
while IFS= read -r f; do
  [[ -n "$f" ]] || continue
  excluded "$f" || files+=("$f")
done < <(git diff --cached --name-only --diff-filter=ACMR)
(( ${#files[@]} )) || exit 0

git diff --cached --no-color --no-ext-diff -U0 -- "${files[@]}" | RULES="$rules" awk '
  function esc(s) { gsub(/[][\\.^$*+?(){}|\/]/, "\\\\&", s); return s }
  function idch(c) { return c ~ /[a-z0-9_-]/ }
  BEGIN {
    n = split(ENVIRON["RULES"], r, "\n")
    for (i = 1; i <= n; i++) { split(r[i], p, "\t"); kind[i] = p[1]; syn[i] = p[2]; term[i] = p[3] }
    fail = 0
  }
  /^\+\+\+ / { file = substr($0, 5); sub(/^b\//, "", file); next }
  /^@@ / { match($0, /\+[0-9]+/); line = substr($0, RSTART + 1, RLENGTH - 1) + 0; next }
  /^\+/ {
    text = tolower(substr($0, 2))
    for (i = 1; i <= n; i++) {
      t = text
      # The term itself is never a hit, even when a synonym is part of it.
      gsub(esc(tolower(term[i])), sprintf("%" length(term[i]) "s", ""), t)
      s = t; off = 0
      while ((pos = index(s, syn[i])) > 0) {
        start = off + pos; end = start + length(syn[i])
        before = (start > 1) ? substr(t, start - 1, 1) : " "
        after = substr(t, end, 1); if (after == "") after = " "
        if (kind[i] == "anywhere" || (!idch(before) && !idch(after))) {
          printf "rule: vocabulary: %s:%d: \"%s\" is a banned synonym. Use \"%s\".\n", file, line, syn[i], term[i] > "/dev/stderr"
          fail = 1
          break
        }
        s = substr(t, end); off = end - 1
      }
    }
    line++
  }
  END { exit fail }
'
