package com.mantel.kernel

import java.nio.ByteBuffer
import java.security.SecureRandom
import java.util.UUID

/**
 * Unguessable public identifiers, and time-ordered internal ones.
 *
 * A share-link token is 12 characters of the alphabet below, about 71 bits (SDD.md 4.3).
 *
 * A row id is a UUIDv7: 48 bits of millisecond timestamp followed by random bits. Rows written
 * together land together in the index instead of scattering across it, which matters because items
 * arrive forty at a time and the claim loop reads them in creation order. A v7 id carries its
 * creation time; that is acceptable here because row ids are seen only by the account that owns
 * them, and a share token is generated by a different function.
 */
object Ids {
    private const val ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZabcdefghijkmnpqrstvwxyz"
    private val random = SecureRandom()

    fun token(length: Int = 12): String {
        val out = StringBuilder(length)
        repeat(length) { out.append(ALPHABET[random.nextInt(ALPHABET.length)]) }
        return out.toString()
    }

    fun uuidV7(clock: Clock = Clock.system): UUID {
        val bytes = ByteArray(10).also(random::nextBytes)
        val millis = clock.now().toEpochMilli()

        var high = millis shl 16
        // Version 7 in the top nibble of the seventh byte, then random bits.
        high = high or 0x7000L or ((bytes[0].toLong() and 0x0F) shl 8) or (bytes[1].toLong() and 0xFF)

        // Variant 10 in the top two bits, random for the rest.
        val low = (ByteBuffer.wrap(bytes, 2, 8).long and 0x3FFFFFFFFFFFFFFFL) or (0b10L shl 62)

        return UUID(high, low)
    }
}
